language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - dh-autoreconf
    - automake
before_install:
- sudo apt-get install pccts -y
- secure: bEUDsWHOHHk0zUH0eXP4MFjEINIzNX5mt31zKGvK/RcLuQN6sUwuaAczeqf4dNuI+Ysfl8hWoM4McvzAuEk22xaMF6tNc12YXafbQolet4KMQpykKG3P36u+QeS21JmkTISRVODCr5v2zN8Tc1xaN+XdRGIJ17iMtdArVfENWnGqeJKpVEEGcziejY/CcpqPaZIoaL8crJobBxwDS1ET9vkbFWaNiOFQiGyqotfsrnQABeiB0y1rDOsRqI6W3Z88U8InJtdBMywwo6MRYUHJxyTw03zfv21JOzuR6W4aJC4ctfJLqYbhvSTXbYjE81dBjDvGZVqMLajYCHblG9kqO+4XwgitxBeDzHyQ5JyGk0h5c9J40lyXzHH7F4N6YOShL7I+1JRZi54Ip704ntwJZiqhOynwU625/IHTkbTpdQw+dFLip0qpJbuFLQ/j5adgDw9LemdUPvvILVrrjaj+IaLV1zSa4DWSHQuhN9OxprnJByREKe4VHNL6vG2mLva6le6ODRB0GCz4xedneQnIeg7kQuQQd07FybZLhCMQUAiQDi/boMRwptBB7mYF4DfTqx3QwN/JVk9+cns9IbJc63tXIdMUnSD3TDcFbvw9qmVTdYjK8QSpquJ67vZL/pZEtGTkY56z2e11sgFRDQMmRXYyf5HL64pXJKZDbHeSTj8=
- echo $SOMEVAR
- dh_autoreconf
